apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
data:
{{- $root := . -}}
{{- range $key, $value := .Values.ruleFiles }}
  {{ $key }}: {{- toYaml $value | indent 2 }}
{{- end }}
{{- range $key, $value := .Values.serverFiles }}
  {{ $key }}: |
{{- if eq $key "prometheus.yml" }}
    global:
{{ $root.Values.server.global | toYaml | trimSuffix "\n" | indent 6 }}

{{- if empty $root.Values.server.remoteWrite }}
    remote_write:
    - url: http://{{ include "prometheusesadapter.fullname" $ }}:{{ $root.Values.prometheusesadapter.service.ports.pea8000.port }}/write
{{- else }}
    remote_write:
{{ $root.Values.server.remoteWrite | toYaml | indent 4 }}
{{- end }}

{{- if empty $root.Values.server.remoteRead }}
    remote_read:
    - url: http://{{ include "prometheusesadapter.fullname" $ }}:{{ $root.Values.prometheusesadapter.service.ports.pea8000.port }}/read
{{- else }}
    remote_read:
{{ $root.Values.server.remoteRead | toYaml | indent 4 }}
{{- end }}

{{- end }}

{{- if eq $key "alerts" }}
{{- if and (not (empty $value)) (empty $value.groups) }}
    groups:
{{- range $ruleKey, $ruleValue := $value }}
    - name: {{ $ruleKey -}}.rules
      rules:
{{ $ruleValue | toYaml | trimSuffix "\n" | indent 6 }}
{{- end }}
{{- else }}
{{ toYaml $value | indent 4 }}
{{- end }}
{{- else }}
{{ toYaml $value | default "{}" | indent 4 }}
{{- end }}

{{- if eq $key "prometheus.yml" -}}
#{{- if $root.Values.extraScrapeConfigs }}
#{{ tpl $root.Values.extraScrapeConfigs $root | indent 4 }}
#{{- end -}}

{{ printf "\n" }}
    scrape_configs:
    - job_name: prometheus
      static_configs:
        - targets:
          - localhost:9090

    - job_name: Httpsd-Targets
      http_sd_configs:
        - url: http://{{ include "targetapi.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $root.Values.targetapi.service.ports.targetapi.port }}
 
    - job_name: Node_exporter
      static_configs:
        - targets:
          - {{ $.Release.Name }}-prometheus-node-exporter.{{ $.Release.Namespace }}.svc.cluster.local:9100

    - job_name: kube-state-metrics
      static_configs:
        - targets:
          - {{ $.Release.Name }}-kube-state-metrics.{{ $.Release.Namespace }}.svc.cluster.local:8080

{{- end }}
{{- end }}
