apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "server.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: storage-volume
  resources:
    requests:
      storage: 3Gi