apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.globalService }}
    {{- include "globalServiceAnnotations" . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: server
      port: {{ .Values.server.service.ports.server.port }}
      targetPort: {{ .Values.server.service.ports.server.targetPort }}
      protocol: {{ .Values.server.service.ports.server.protocol }}
      {{- if and (or (eq .Values.server.service.type "NodePort") (eq .Values.server.service.type "LoadBalancer")) (not (empty .Values.server.service.ports.server.nodePort)) }}
      nodePort: {{ .Values.server.service.ports.server.nodePort }}
      {{- end }}
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}
